// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import {describe, it} from 'mocha';
import * as sipinfoserviceModule from '../src';

import {protobuf} from 'google-gax';

function generateSampleMessage<T extends object>(instance: T) {
  const filledObject = (
    instance.constructor as typeof protobuf.Message
  ).toObject(instance as protobuf.Message<T>, {defaults: true});
  return (instance.constructor as typeof protobuf.Message).fromObject(
    filledObject
  ) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
  return error
    ? sinon.stub().rejects(error)
    : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(
  response?: ResponseType,
  error?: Error
) {
  return error
    ? sinon.stub().callsArgWith(2, error)
    : sinon.stub().callsArgWith(2, null, response);
}

describe('v1beta1.SipInfoServiceClient', () => {
  it('has servicePath', () => {
    const servicePath =
      sipinfoserviceModule.v1beta1.SipInfoServiceClient.servicePath;
    assert(servicePath);
  });

  it('has apiEndpoint', () => {
    const apiEndpoint =
      sipinfoserviceModule.v1beta1.SipInfoServiceClient.apiEndpoint;
    assert(apiEndpoint);
  });

  it('has port', () => {
    const port = sipinfoserviceModule.v1beta1.SipInfoServiceClient.port;
    assert(port);
    assert(typeof port === 'number');
  });

  it('should create a client with no option', () => {
    const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient();
    assert(client);
  });

  it('should create a client with gRPC fallback', () => {
    const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
      fallback: true,
    });
    assert(client);
  });

  it('has initialize method and supports deferred initialization', async () => {
    const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    assert.strictEqual(client.sipInfoServiceStub, undefined);
    await client.initialize();
    assert(client.sipInfoServiceStub);
  });

  it('has close method', () => {
    const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.close();
  });

  it('has getProjectId method', async () => {
    const fakeProjectId = 'fake-project-id';
    const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
    const result = await client.getProjectId();
    assert.strictEqual(result, fakeProjectId);
    assert((client.auth.getProjectId as SinonStub).calledWithExactly());
  });

  it('has getProjectId method with callback', async () => {
    const fakeProjectId = 'fake-project-id';
    const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.auth.getProjectId = sinon
      .stub()
      .callsArgWith(0, null, fakeProjectId);
    const promise = new Promise((resolve, reject) => {
      client.getProjectId((err?: Error | null, projectId?: string | null) => {
        if (err) {
          reject(err);
        } else {
          resolve(projectId);
        }
      });
    });
    const result = await promise;
    assert.strictEqual(result, fakeProjectId);
  });

  describe('getSipInfo', () => {
    it('invokes getSipInfo without error', async () => {
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.voice.v1beta1.GetSipInfoRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.voice.v1beta1.SipInfo()
      );
      client.innerApiCalls.getSipInfo = stubSimpleCall(expectedResponse);
      const [response] = await client.getSipInfo(request);
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.getSipInfo as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes getSipInfo without error using callback', async () => {
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.voice.v1beta1.GetSipInfoRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.voice.v1beta1.SipInfo()
      );
      client.innerApiCalls.getSipInfo =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getSipInfo(
          request,
          (
            err?: Error | null,
            result?: protos.enfonica.voice.v1beta1.ISipInfo | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.getSipInfo as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions /*, callback defined above */)
      );
    });

    it('invokes getSipInfo with error', async () => {
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.voice.v1beta1.GetSipInfoRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.innerApiCalls.getSipInfo = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.getSipInfo(request), expectedError);
      assert(
        (client.innerApiCalls.getSipInfo as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
  });

  describe('Path templates', () => {
    describe('alias', () => {
      const fakePath = '/rendered/path/alias';
      const expectedParameters = {
        project: 'projectValue',
        sip_domain: 'sipDomainValue',
        alias: 'aliasValue',
      };
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.aliasPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.aliasPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('aliasPath', () => {
        const result = client.aliasPath(
          'projectValue',
          'sipDomainValue',
          'aliasValue'
        );
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.aliasPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromAliasName', () => {
        const result = client.matchProjectFromAliasName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.aliasPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchSipDomainFromAliasName', () => {
        const result = client.matchSipDomainFromAliasName(fakePath);
        assert.strictEqual(result, 'sipDomainValue');
        assert(
          (client.pathTemplates.aliasPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchAliasFromAliasName', () => {
        const result = client.matchAliasFromAliasName(fakePath);
        assert.strictEqual(result, 'aliasValue');
        assert(
          (client.pathTemplates.aliasPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });

    describe('call', () => {
      const fakePath = '/rendered/path/call';
      const expectedParameters = {
        project: 'projectValue',
        call: 'callValue',
      };
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.callPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.callPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('callPath', () => {
        const result = client.callPath('projectValue', 'callValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.callPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromCallName', () => {
        const result = client.matchProjectFromCallName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.callPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchCallFromCallName', () => {
        const result = client.matchCallFromCallName(fakePath);
        assert.strictEqual(result, 'callValue');
        assert(
          (client.pathTemplates.callPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });

    describe('recording', () => {
      const fakePath = '/rendered/path/recording';
      const expectedParameters = {
        project: 'projectValue',
        call: 'callValue',
        recording: 'recordingValue',
      };
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.recordingPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.recordingPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('recordingPath', () => {
        const result = client.recordingPath(
          'projectValue',
          'callValue',
          'recordingValue'
        );
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.recordingPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromRecordingName', () => {
        const result = client.matchProjectFromRecordingName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.recordingPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchCallFromRecordingName', () => {
        const result = client.matchCallFromRecordingName(fakePath);
        assert.strictEqual(result, 'callValue');
        assert(
          (client.pathTemplates.recordingPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchRecordingFromRecordingName', () => {
        const result = client.matchRecordingFromRecordingName(fakePath);
        assert.strictEqual(result, 'recordingValue');
        assert(
          (client.pathTemplates.recordingPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });

    describe('sipDomain', () => {
      const fakePath = '/rendered/path/sipDomain';
      const expectedParameters = {
        project: 'projectValue',
        sip_domain: 'sipDomainValue',
      };
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.sipDomainPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.sipDomainPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('sipDomainPath', () => {
        const result = client.sipDomainPath('projectValue', 'sipDomainValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.sipDomainPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromSipDomainName', () => {
        const result = client.matchProjectFromSipDomainName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.sipDomainPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchSipDomainFromSipDomainName', () => {
        const result = client.matchSipDomainFromSipDomainName(fakePath);
        assert.strictEqual(result, 'sipDomainValue');
        assert(
          (client.pathTemplates.sipDomainPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });

    describe('sipInfo', () => {
      const fakePath = '/rendered/path/sipInfo';
      const expectedParameters = {
        project: 'projectValue',
        call: 'callValue',
      };
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.sipInfoPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.sipInfoPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('sipInfoPath', () => {
        const result = client.sipInfoPath('projectValue', 'callValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.sipInfoPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromSipInfoName', () => {
        const result = client.matchProjectFromSipInfoName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.sipInfoPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchCallFromSipInfoName', () => {
        const result = client.matchCallFromSipInfoName(fakePath);
        assert.strictEqual(result, 'callValue');
        assert(
          (client.pathTemplates.sipInfoPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });

    describe('transcription', () => {
      const fakePath = '/rendered/path/transcription';
      const expectedParameters = {
        project: 'projectValue',
        call: 'callValue',
        transcription: 'transcriptionValue',
      };
      const client = new sipinfoserviceModule.v1beta1.SipInfoServiceClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.transcriptionPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.transcriptionPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('transcriptionPath', () => {
        const result = client.transcriptionPath(
          'projectValue',
          'callValue',
          'transcriptionValue'
        );
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.transcriptionPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromTranscriptionName', () => {
        const result = client.matchProjectFromTranscriptionName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.transcriptionPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchCallFromTranscriptionName', () => {
        const result = client.matchCallFromTranscriptionName(fakePath);
        assert.strictEqual(result, 'callValue');
        assert(
          (client.pathTemplates.transcriptionPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchTranscriptionFromTranscriptionName', () => {
        const result = client.matchTranscriptionFromTranscriptionName(fakePath);
        assert.strictEqual(result, 'transcriptionValue');
        assert(
          (client.pathTemplates.transcriptionPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });
  });
});
