// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as v1beta1 from './v1beta1';
const AliasesClient = v1beta1.AliasesClient;
const CallsClient = v1beta1.CallsClient;
const RecordingsClient = v1beta1.RecordingsClient;
const SipDomainsClient = v1beta1.SipDomainsClient;
const SipInfoServiceClient = v1beta1.SipInfoServiceClient;
const StreamsClient = v1beta1.StreamsClient;
const TranscriptionsClient = v1beta1.TranscriptionsClient;
export {
  v1beta1,
  AliasesClient,
  CallsClient,
  RecordingsClient,
  SipDomainsClient,
  SipInfoServiceClient,
  StreamsClient,
  TranscriptionsClient,
};
export default {
  v1beta1,
  AliasesClient,
  CallsClient,
  RecordingsClient,
  SipDomainsClient,
  SipInfoServiceClient,
  StreamsClient,
  TranscriptionsClient,
};
import * as protos from '../protos/protos';
export {protos};
