// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import {describe, it} from 'mocha';
import * as unsubscribersModule from '../src';

import {PassThrough} from 'stream';

import {protobuf} from 'google-gax';

function generateSampleMessage<T extends object>(instance: T) {
  const filledObject = (
    instance.constructor as typeof protobuf.Message
  ).toObject(instance as protobuf.Message<T>, {defaults: true});
  return (instance.constructor as typeof protobuf.Message).fromObject(
    filledObject
  ) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
  return error
    ? sinon.stub().rejects(error)
    : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(
  response?: ResponseType,
  error?: Error
) {
  return error
    ? sinon.stub().callsArgWith(2, error)
    : sinon.stub().callsArgWith(2, null, response);
}

function stubPageStreamingCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error
) {
  const pagingStub = sinon.stub();
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
    }
  }
  const transformStub = error
    ? sinon.stub().callsArgWith(2, error)
    : pagingStub;
  const mockStream = new PassThrough({
    objectMode: true,
    transform: transformStub,
  });
  // trigger as many responses as needed
  if (responses) {
    for (let i = 0; i < responses.length; ++i) {
      setImmediate(() => {
        mockStream.write({});
      });
    }
    setImmediate(() => {
      mockStream.end();
    });
  } else {
    setImmediate(() => {
      mockStream.write({});
    });
    setImmediate(() => {
      mockStream.end();
    });
  }
  return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(
  responses?: ResponseType[],
  error?: Error
) {
  let counter = 0;
  const asyncIterable = {
    [Symbol.asyncIterator]() {
      return {
        async next() {
          if (error) {
            return Promise.reject(error);
          }
          if (counter >= responses!.length) {
            return Promise.resolve({done: true, value: undefined});
          }
          return Promise.resolve({done: false, value: responses![counter++]});
        },
      };
    },
  };
  return sinon.stub().returns(asyncIterable);
}

describe('v1.UnsubscribersClient', () => {
  it('has servicePath', () => {
    const servicePath = unsubscribersModule.v1.UnsubscribersClient.servicePath;
    assert(servicePath);
  });

  it('has apiEndpoint', () => {
    const apiEndpoint = unsubscribersModule.v1.UnsubscribersClient.apiEndpoint;
    assert(apiEndpoint);
  });

  it('has port', () => {
    const port = unsubscribersModule.v1.UnsubscribersClient.port;
    assert(port);
    assert(typeof port === 'number');
  });

  it('should create a client with no option', () => {
    const client = new unsubscribersModule.v1.UnsubscribersClient();
    assert(client);
  });

  it('should create a client with gRPC fallback', () => {
    const client = new unsubscribersModule.v1.UnsubscribersClient({
      fallback: true,
    });
    assert(client);
  });

  it('has initialize method and supports deferred initialization', async () => {
    const client = new unsubscribersModule.v1.UnsubscribersClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    assert.strictEqual(client.unsubscribersStub, undefined);
    await client.initialize();
    assert(client.unsubscribersStub);
  });

  it('has close method', () => {
    const client = new unsubscribersModule.v1.UnsubscribersClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.close();
  });

  it('has getProjectId method', async () => {
    const fakeProjectId = 'fake-project-id';
    const client = new unsubscribersModule.v1.UnsubscribersClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
    const result = await client.getProjectId();
    assert.strictEqual(result, fakeProjectId);
    assert((client.auth.getProjectId as SinonStub).calledWithExactly());
  });

  it('has getProjectId method with callback', async () => {
    const fakeProjectId = 'fake-project-id';
    const client = new unsubscribersModule.v1.UnsubscribersClient({
      credentials: {client_email: 'bogus', private_key: 'bogus'},
      projectId: 'bogus',
    });
    client.auth.getProjectId = sinon
      .stub()
      .callsArgWith(0, null, fakeProjectId);
    const promise = new Promise((resolve, reject) => {
      client.getProjectId((err?: Error | null, projectId?: string | null) => {
        if (err) {
          reject(err);
        } else {
          resolve(projectId);
        }
      });
    });
    const result = await promise;
    assert.strictEqual(result, fakeProjectId);
  });

  describe('createUnsubscriber', () => {
    it('invokes createUnsubscriber without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.CreateUnsubscriberRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.createUnsubscriber =
        stubSimpleCall(expectedResponse);
      const [response] = await client.createUnsubscriber(request);
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.createUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes createUnsubscriber without error using callback', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.CreateUnsubscriberRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.createUnsubscriber =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.createUnsubscriber(
          request,
          (
            err?: Error | null,
            result?: protos.enfonica.messaging.v1.IUnsubscriber | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.createUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions /*, callback defined above */)
      );
    });

    it('invokes createUnsubscriber with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.CreateUnsubscriberRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.innerApiCalls.createUnsubscriber = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.createUnsubscriber(request), expectedError);
      assert(
        (client.innerApiCalls.createUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
  });

  describe('getUnsubscriber', () => {
    it('invokes getUnsubscriber without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.GetUnsubscriberRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.getUnsubscriber = stubSimpleCall(expectedResponse);
      const [response] = await client.getUnsubscriber(request);
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.getUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes getUnsubscriber without error using callback', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.GetUnsubscriberRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.getUnsubscriber =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.getUnsubscriber(
          request,
          (
            err?: Error | null,
            result?: protos.enfonica.messaging.v1.IUnsubscriber | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.getUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions /*, callback defined above */)
      );
    });

    it('invokes getUnsubscriber with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.GetUnsubscriberRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.innerApiCalls.getUnsubscriber = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.getUnsubscriber(request), expectedError);
      assert(
        (client.innerApiCalls.getUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
  });

  describe('updateUnsubscriber', () => {
    it('invokes updateUnsubscriber without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.UpdateUnsubscriberRequest()
      );
      request.unsubscriber = {};
      request.unsubscriber.name = '';
      const expectedHeaderRequestParams = 'unsubscriber.name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.updateUnsubscriber =
        stubSimpleCall(expectedResponse);
      const [response] = await client.updateUnsubscriber(request);
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.updateUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes updateUnsubscriber without error using callback', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.UpdateUnsubscriberRequest()
      );
      request.unsubscriber = {};
      request.unsubscriber.name = '';
      const expectedHeaderRequestParams = 'unsubscriber.name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.updateUnsubscriber =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.updateUnsubscriber(
          request,
          (
            err?: Error | null,
            result?: protos.enfonica.messaging.v1.IUnsubscriber | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.updateUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions /*, callback defined above */)
      );
    });

    it('invokes updateUnsubscriber with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.UpdateUnsubscriberRequest()
      );
      request.unsubscriber = {};
      request.unsubscriber.name = '';
      const expectedHeaderRequestParams = 'unsubscriber.name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.innerApiCalls.updateUnsubscriber = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.updateUnsubscriber(request), expectedError);
      assert(
        (client.innerApiCalls.updateUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
  });

  describe('deleteUnsubscriber', () => {
    it('invokes deleteUnsubscriber without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.DeleteUnsubscriberRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.deleteUnsubscriber =
        stubSimpleCall(expectedResponse);
      const [response] = await client.deleteUnsubscriber(request);
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.deleteUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes deleteUnsubscriber without error using callback', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.DeleteUnsubscriberRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = generateSampleMessage(
        new protos.enfonica.messaging.v1.Unsubscriber()
      );
      client.innerApiCalls.deleteUnsubscriber =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.deleteUnsubscriber(
          request,
          (
            err?: Error | null,
            result?: protos.enfonica.messaging.v1.IUnsubscriber | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.deleteUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions /*, callback defined above */)
      );
    });

    it('invokes deleteUnsubscriber with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.DeleteUnsubscriberRequest()
      );
      request.name = '';
      const expectedHeaderRequestParams = 'name=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.innerApiCalls.deleteUnsubscriber = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.deleteUnsubscriber(request), expectedError);
      assert(
        (client.innerApiCalls.deleteUnsubscriber as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });
  });

  describe('listUnsubscribers', () => {
    it('invokes listUnsubscribers without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = [
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
      ];
      client.innerApiCalls.listUnsubscribers = stubSimpleCall(expectedResponse);
      const [response] = await client.listUnsubscribers(request);
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.listUnsubscribers as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes listUnsubscribers without error using callback', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedResponse = [
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
      ];
      client.innerApiCalls.listUnsubscribers =
        stubSimpleCallWithCallback(expectedResponse);
      const promise = new Promise((resolve, reject) => {
        client.listUnsubscribers(
          request,
          (
            err?: Error | null,
            result?: protos.enfonica.messaging.v1.IUnsubscriber[] | null
          ) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          }
        );
      });
      const response = await promise;
      assert.deepStrictEqual(response, expectedResponse);
      assert(
        (client.innerApiCalls.listUnsubscribers as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions /*, callback defined above */)
      );
    });

    it('invokes listUnsubscribers with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedOptions = {
        otherArgs: {
          headers: {
            'x-goog-request-params': expectedHeaderRequestParams,
          },
        },
      };
      const expectedError = new Error('expected');
      client.innerApiCalls.listUnsubscribers = stubSimpleCall(
        undefined,
        expectedError
      );
      await assert.rejects(client.listUnsubscribers(request), expectedError);
      assert(
        (client.innerApiCalls.listUnsubscribers as SinonStub)
          .getCall(0)
          .calledWith(request, expectedOptions, undefined)
      );
    });

    it('invokes listUnsubscribersStream without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedResponse = [
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
      ];
      client.descriptors.page.listUnsubscribers.createStream =
        stubPageStreamingCall(expectedResponse);
      const stream = client.listUnsubscribersStream(request);
      const promise = new Promise((resolve, reject) => {
        const responses: protos.enfonica.messaging.v1.Unsubscriber[] = [];
        stream.on(
          'data',
          (response: protos.enfonica.messaging.v1.Unsubscriber) => {
            responses.push(response);
          }
        );
        stream.on('end', () => {
          resolve(responses);
        });
        stream.on('error', (err: Error) => {
          reject(err);
        });
      });
      const responses = await promise;
      assert.deepStrictEqual(responses, expectedResponse);
      assert(
        (client.descriptors.page.listUnsubscribers.createStream as SinonStub)
          .getCall(0)
          .calledWith(client.innerApiCalls.listUnsubscribers, request)
      );
      assert.strictEqual(
        (
          client.descriptors.page.listUnsubscribers.createStream as SinonStub
        ).getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
        expectedHeaderRequestParams
      );
    });

    it('invokes listUnsubscribersStream with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedError = new Error('expected');
      client.descriptors.page.listUnsubscribers.createStream =
        stubPageStreamingCall(undefined, expectedError);
      const stream = client.listUnsubscribersStream(request);
      const promise = new Promise((resolve, reject) => {
        const responses: protos.enfonica.messaging.v1.Unsubscriber[] = [];
        stream.on(
          'data',
          (response: protos.enfonica.messaging.v1.Unsubscriber) => {
            responses.push(response);
          }
        );
        stream.on('end', () => {
          resolve(responses);
        });
        stream.on('error', (err: Error) => {
          reject(err);
        });
      });
      await assert.rejects(promise, expectedError);
      assert(
        (client.descriptors.page.listUnsubscribers.createStream as SinonStub)
          .getCall(0)
          .calledWith(client.innerApiCalls.listUnsubscribers, request)
      );
      assert.strictEqual(
        (
          client.descriptors.page.listUnsubscribers.createStream as SinonStub
        ).getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
        expectedHeaderRequestParams
      );
    });

    it('uses async iteration with listUnsubscribers without error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedResponse = [
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
        generateSampleMessage(new protos.enfonica.messaging.v1.Unsubscriber()),
      ];
      client.descriptors.page.listUnsubscribers.asyncIterate =
        stubAsyncIterationCall(expectedResponse);
      const responses: protos.enfonica.messaging.v1.IUnsubscriber[] = [];
      const iterable = client.listUnsubscribersAsync(request);
      for await (const resource of iterable) {
        responses.push(resource!);
      }
      assert.deepStrictEqual(responses, expectedResponse);
      assert.deepStrictEqual(
        (
          client.descriptors.page.listUnsubscribers.asyncIterate as SinonStub
        ).getCall(0).args[1],
        request
      );
      assert.strictEqual(
        (
          client.descriptors.page.listUnsubscribers.asyncIterate as SinonStub
        ).getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
        expectedHeaderRequestParams
      );
    });

    it('uses async iteration with listUnsubscribers with error', async () => {
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      const request = generateSampleMessage(
        new protos.enfonica.messaging.v1.ListUnsubscribersRequest()
      );
      request.parent = '';
      const expectedHeaderRequestParams = 'parent=';
      const expectedError = new Error('expected');
      client.descriptors.page.listUnsubscribers.asyncIterate =
        stubAsyncIterationCall(undefined, expectedError);
      const iterable = client.listUnsubscribersAsync(request);
      await assert.rejects(async () => {
        const responses: protos.enfonica.messaging.v1.IUnsubscriber[] = [];
        for await (const resource of iterable) {
          responses.push(resource!);
        }
      });
      assert.deepStrictEqual(
        (
          client.descriptors.page.listUnsubscribers.asyncIterate as SinonStub
        ).getCall(0).args[1],
        request
      );
      assert.strictEqual(
        (
          client.descriptors.page.listUnsubscribers.asyncIterate as SinonStub
        ).getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
        expectedHeaderRequestParams
      );
    });
  });

  describe('Path templates', () => {
    describe('message', () => {
      const fakePath = '/rendered/path/message';
      const expectedParameters = {
        project: 'projectValue',
        message: 'messageValue',
      };
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.messagePathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.messagePathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('messagePath', () => {
        const result = client.messagePath('projectValue', 'messageValue');
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.messagePathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromMessageName', () => {
        const result = client.matchProjectFromMessageName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.messagePathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchMessageFromMessageName', () => {
        const result = client.matchMessageFromMessageName(fakePath);
        assert.strictEqual(result, 'messageValue');
        assert(
          (client.pathTemplates.messagePathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });

    describe('unsubscriber', () => {
      const fakePath = '/rendered/path/unsubscriber';
      const expectedParameters = {
        project: 'projectValue',
        unsubscriber: 'unsubscriberValue',
      };
      const client = new unsubscribersModule.v1.UnsubscribersClient({
        credentials: {client_email: 'bogus', private_key: 'bogus'},
        projectId: 'bogus',
      });
      client.initialize();
      client.pathTemplates.unsubscriberPathTemplate.render = sinon
        .stub()
        .returns(fakePath);
      client.pathTemplates.unsubscriberPathTemplate.match = sinon
        .stub()
        .returns(expectedParameters);

      it('unsubscriberPath', () => {
        const result = client.unsubscriberPath(
          'projectValue',
          'unsubscriberValue'
        );
        assert.strictEqual(result, fakePath);
        assert(
          (client.pathTemplates.unsubscriberPathTemplate.render as SinonStub)
            .getCall(-1)
            .calledWith(expectedParameters)
        );
      });

      it('matchProjectFromUnsubscriberName', () => {
        const result = client.matchProjectFromUnsubscriberName(fakePath);
        assert.strictEqual(result, 'projectValue');
        assert(
          (client.pathTemplates.unsubscriberPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });

      it('matchUnsubscriberFromUnsubscriberName', () => {
        const result = client.matchUnsubscriberFromUnsubscriberName(fakePath);
        assert.strictEqual(result, 'unsubscriberValue');
        assert(
          (client.pathTemplates.unsubscriberPathTemplate.match as SinonStub)
            .getCall(-1)
            .calledWith(fakePath)
        );
      });
    });
  });
});
